/**
 * tiktok shop openapi
 * sdk for apis
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from '../../models';
import { AffiliateSeller202508CreateTargetCollaborationResponseDataTargetCollaboration } from './CreateTargetCollaborationResponseDataTargetCollaboration';
import { AffiliateSeller202508CreateTargetCollaborationResponseDataTargetCollaborationConflicts } from './CreateTargetCollaborationResponseDataTargetCollaborationConflicts';

export class AffiliateSeller202508CreateTargetCollaborationResponseData {
    'targetCollaboration'?: AffiliateSeller202508CreateTargetCollaborationResponseDataTargetCollaboration;
    /**
    * A list of user and product identifiers with target collaboration conflicts that caused target collaboration failure. 
    */
    'targetCollaborationConflicts'?: Array<AffiliateSeller202508CreateTargetCollaborationResponseDataTargetCollaborationConflicts>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "targetCollaboration",
            "baseName": "target_collaboration",
            "type": "AffiliateSeller202508CreateTargetCollaborationResponseDataTargetCollaboration"
        },
        {
            "name": "targetCollaborationConflicts",
            "baseName": "target_collaboration_conflicts",
            "type": "Array<AffiliateSeller202508CreateTargetCollaborationResponseDataTargetCollaborationConflicts>"
        }    ];

    static getAttributeTypeMap() {
        return AffiliateSeller202508CreateTargetCollaborationResponseData.attributeTypeMap;
    }
}

